### ISSUE TITLE
Autoscale jobs fail or keep running everytime.

### ISSUE THREAD

**Issue by alaurie** [Azure/RDS-Templates#390]
I've deployed the logic scaling app as documented but it fails everytime.  Anyone else had this issue? No errors output in job run just the below.

![image](https://user-images.githubusercontent.com/1402140/77283328-d301b000-6d17-11ea-8dd4-df6c54178a50.png)

**Comment by LeeSchuenemeyer** [comment]
Same here
![image](https://user-images.githubusercontent.com/44645574/77466092-bcbb2900-6dd7-11ea-87c8-23c918d7e159.png)

**Comment by LeeSchuenemeyer** [comment]
Webhook configuration
![image](https://user-images.githubusercontent.com/44645574/77466174-dfe5d880-6dd7-11ea-8406-d7c82facccb7.png)

**Comment by YariCa** [comment]
Same here.
Please help

**Comment by alaurie** [comment]
Found the issue. The docs are lacking a bit of the process. Follow this video instead.
https://www.youtube.com/watch?v=FYDDmr9XUwo

**Comment by brapoport2020** [comment]
Hi, Could anyone provide more details, I used the video, yet still have the same issue. What is missing?

**Comment by viswanadham-k** [comment]
Hi All,
Thanks for your feedback. 
Did you follow this document (https://docs.microsoft.com/en-us/azure/virtual-desktop/virtual-desktop-fall-2019/set-up-scaling-script) steps to setup wvd scaling tool.

Can you please share with us error message or exception of job. For your reference please find attached screenshot. 
![image](https://user-images.githubusercontent.com/54656839/81340772-07fe7200-90ce-11ea-8e84-a52978697b81.png)


Thanks,

**Comment by brapoport2020** [comment]
I get no error messages. The job just says failed an the output below, nit much in it

[cid:image002.png@01D62555.5FC719E0]
[cid:image004.png@01D62555.5FC719E0]

Errors0

Warnings0
Type:Any
Time
Type
Details
5/8/2020, 4:19:55 PM
Verbose
Loading module from path 'C:\Modules\User\Az.Accounts\Microsoft.Azure.PowerShell.Cmdlets.Accounts.dll'.
5/8/2020, 4:19:55 PM
Verbose
Importing cmdlet 'Get-AzProfile'.
5/8/2020, 4:19:55 PM
Verbose
Importing cmdlet 'Register-AzModule'.
5/8/2020, 4:19:55 PM
Verbose
Importing cmdlet 'Select-AzProfile'.
5/8/2020, 4:19:55 PM
Verbose
Importing cmdlet 'Connect-AzAccount'.
5/8/2020, 4:19:56 PM
Verbose
Importing cmdlet 'Disconnect-AzAccount'.
5/8/2020, 4:19:56 PM
Verbose
Importing cmdlet 'Get-AzContext'.
5/8/2020, 4:19:56 PM
Verbose
Importing cmdlet 'Import-AzContext'.
5/8/2020, 4:19:56 PM
Verbose
Importing cmdlet 'Save-AzContext'.
5/8/2020, 4:19:56 PM
Verbose
Importing cmdlet 'Set-AzContext'.
5/8/2020, 4:19:56 PM
Verbose
Importing cmdlet 'Disable-AzDataCollection'.
5/8/2020, 4:19:56 PM
Verbose
Importing cmdlet 'Enable-AzDataCollection'.
5/8/2020, 4:19:56 PM
Verbose
Importing cmdlet 'Add-AzEnvironment'.
5/8/2020, 4:19:56 PM
Verbose
Importing cmdlet 'Get-AzEnvironment'.
5/8/2020, 4:19:56 PM
Verbose
Importing cmdlet 'Remove-AzEnvironment'.
5/8/2020, 4:19:57 PM
Verbose
Importing cmdlet 'Set-AzEnvironment'.
5/8/2020, 4:19:57 PM
Verbose
Importing cmdlet 'Send-Feedback'.
5/8/2020, 4:19:57 PM
Verbose
Importing cmdlet 'Get-AzSubscription'.
5/8/2020, 4:19:57 PM
Verbose
Importing cmdlet 'Get-AzTenant'.
5/8/2020, 4:19:57 PM
Verbose
Importing cmdlet 'Uninstall-AzureRm'.
5/8/2020, 4:19:57 PM
Verbose
Importing cmdlet 'Resolve-AzError'.
5/8/2020, 4:19:57 PM
Verbose
Importing cmdlet 'Clear-AzDefault'.
5/8/2020, 4:19:57 PM
Verbose
Importing cmdlet 'Get-AzDefault'.
5/8/2020, 4:19:57 PM
Verbose
Importing cmdlet 'Set-AzDefault'.
5/8/2020, 4:19:57 PM
Verbose
Importing cmdlet 'Disable-AzureRmAlias'.
5/8/2020, 4:19:57 PM
Verbose
Importing cmdlet 'Enable-AzureRmAlias'.
5/8/2020, 4:19:58 PM
Verbose
Importing cmdlet 'Disable-AzContextAutosave'.
5/8/2020, 4:19:58 PM
Verbose
Importing cmdlet 'Enable-AzContextAutosave'.
5/8/2020, 4:19:58 PM
Verbose
Importing cmdlet 'Get-AzContextAutosaveSetting'.
5/8/2020, 4:19:58 PM
Verbose
Importing cmdlet 'Clear-AzContext'.
5/8/2020, 4:19:58 PM
Verbose
Importing cmdlet 'Remove-AzContext'.
5/8/2020, 4:19:58 PM
Verbose
Importing cmdlet 'Rename-AzContext'.
5/8/2020, 4:19:58 PM
Verbose
Importing cmdlet 'Select-AzContext'.
5/8/2020, 4:19:58 PM
Verbose
Importing alias 'Login-AzAccount'.
5/8/2020, 4:19:58 PM
Verbose
Importing alias 'Login-AzureRmAccount'.
5/8/2020, 4:19:58 PM
Verbose
Importing alias 'Add-AzAccount'.
5/8/2020, 4:19:59 PM
Verbose
Importing alias 'Logout-AzAccount'.
5/8/2020, 4:19:59 PM
Verbose
Importing alias 'Logout-AzureRmAccount'.
5/8/2020, 4:19:59 PM
Verbose
Importing alias 'Remove-AzAccount'.
5/8/2020, 4:19:59 PM
Verbose
Importing alias 'Save-AzProfile'.
5/8/2020, 4:19:59 PM
Verbose
Importing alias 'Select-AzSubscription'.
5/8/2020, 4:19:59 PM
Verbose
Importing alias 'Get-AzureRmDomain'.
5/8/2020, 4:19:59 PM
Verbose
Importing alias 'Get-AzDomain'.
5/8/2020, 4:19:59 PM
Verbose
Importing alias 'Resolve-Error'.
5/8/2020, 4:20:03 PM
Output
Authenticating as service principal for Azure. Result: Account SubscriptionName TenantId Environment ------- ---------------- -------- ----------- 222a3e04-3855-48bd-97cc-95b2c4d9f357 Microsoft Azure e4382aca-78a9-47f8-be5b-73cf0879eff4 AzureCloud
5/8/2020, 4:20:04 PM
Output
Sets the Azure subscription. Result: Name Account SubscriptionName Environment TenantId ---- ------- ---------------- ----------- -------- Microsoft Azure (79970aef-39c9-4421-8... 222a3e04-3855-48... Microsoft Azure AzureCloud e4382aca-78a9-47...
5/8/2020, 4:20:05 PM
Output
Authenticating as service principal for WVD. Result: DeploymentUrl TenantGroupName UserName ------------- --------------- -------- https://rdbroker.wvd.microsoft.com Default Tenant Group Certificate
5/8/2020, 4:20:06 PM
Output
Starting WVD tenant hosts scale optimization: Current Date Time is: 05/08/2020 15:20:05
5/8/2020, 4:20:09 PM
Output
It is in peak hours now
5/8/2020, 4:20:09 PM
Output
Starting session hosts as needed based on current workloads.
5/8/2020, 4:20:24 PM
Output
Checking session host: ArchitNoGpu-0.getarchit.com of sessions: 0 and status: Unavailable


[cid:image006.png@01D62555.5FC719E0]
Boris Rapoport
CEO - ArchIT
415 745 9501
boris.rapoport@getarchit.com<mailto:boris.rapoport@getarchit.com> | www.getarchit.com<http://www.getarchit.com/>

Providing better IT support for Architectural Design and Engineering community!
[facebook]<https://www.facebook.com/ArchITSF/>      [linkedin] <https://www.linkedin.com/company/18321773/>        [twitter] <https://twitter.com/ArchIT_SF>

**Comment by viswanadham-k** [comment]
Hi All,
We have fixed your issue in latest bits. So can you please follow the below steps and update the latest changes.

Below are the steps to update the Azure automation-based scaling tool located here to latest version
Access below link and copy the content of basicScale.ps1 code into a clipboard
https://raw.githubusercontent.com/Azure/RDS-Templates/master/wvd-templates/wvd-scaling-script/basicScale.ps1

Login to the Azure portal
In the Azure portal, select All services. In the list of resources, enter and select Automation Accounts.
On the Automation Accounts page, select the name of Automation account where you have the scaling tool hosted
Click on Runbooks under Process Automation section on the left hand side pane.
Click on PowerShell Runbook named “WVDAutoScaleRunbook”
Click on Edit from the top pane
Replace the existing code with one from Step 1
Click “Save” and “Publish”
New code will come into effect from next run of the runbook based on recurrence interval you have scheduled.

Please let me know if you are still facing issues. If it is working fine then close this issue.

Thanks

**Comment by brapoport2020** [comment]
Hi. Now the Jobs are stuck in RUNNING state. Still, no automation is happening

**Comment by brapoport2020** [comment]
![image](https://user-images.githubusercontent.com/63267682/82011001-8e640800-9628-11ea-8e5f-266d1df9c258.png)

**Comment by rubenz91** [comment]
I have the same issue as you. I had complete the whole process, even delete everything and start from 0 (To check I didn't mess with anything). When I created everything following the steps, it failed always and keeps running. So I check the video https://www.youtube.com/watch?v=FYDDmr9XUwo and complete adding the webhook and still failed this time showing the same large output message as your post brapoport2020.

No warnings, no errors, just failed.

Any possible steps we are missing?
<img width="1259" alt="Screen Shot 2020-05-21 at 20 07 32" src="https://user-images.githubusercontent.com/29737870/82624048-eeb1f700-9b9e-11ea-83b7-cb19188e79b1.png">
<img width="1259" alt="Screen Shot 2020-05-21 at 20 07 16" src="https://user-images.githubusercontent.com/29737870/82624051-efe32400-9b9e-11ea-86ca-4e7490eaa49a.png">

**Comment by RoopChevuri** [comment]
Can you please validate if you still see the issue with latest version here:  https://github.com/nakranimohit0/azure-docs/blob/yammer_private_preview_wvd_scaling/articles/virtual-desktop/virtual-desktop-fall-2019/set-up-scaling-script.md . We are planning to release this broadly in a few weeks time.

**Comment by nakranimohit0** [comment]
Closing this out. Please re open if you are still running into the same issue even with the newer version
